#!perl

sub hook_deposit_methods($class, $message, $hash, @) {
    $$message =  <<"END";

Please type one of the following:

'iban':      IBAN transfer (Min 10 EUR / NL89 RABO 0111 7413 86)
'cash':      Cash in the cash box
'reimburse': Reimbursement of expenses agreed upon in advance
             Note #1: we require an invoice or receipt with this exact amount!
             Note #2: please do not use this plugin for amounts >20 EUR
'other':     Provide a manual description
END

    %$hash = (
        iban => { description => "Deposit (IBAN transfer)" },
        cash => { description => "Deposit (Cash)" },
        other => { description => "Deposit (%s)", prompts => [ "Description" ] },
        reimburse => {
            description => "Reimbursement (%s, approval: %s)",
            prompts => [
                "Please provide a short description",
                "Which board member gave approval?",
            ],
        },
    );
}
